[package]
name = "Sigma0"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = "3.2.0"
serde_json = "1.0.120"
ureq = { version = "2.10.0", features = ["json"] }

[profile.release]
codegen-units = 1
opt-level = "s"
strip = true
lto = true
